name = "ansury-systems"
compatibility_date = "2024-01-15"

[env.production]
name = "ansury-systems"

[[env.production.vars]]
GEMINI_API_KEY = "..."

[build]
command = "npm run build"
cwd = "."

[site]
bucket = "./dist"
